### ISSUE TITLE
Way to Distinguish Between Communication and Not Found errors in Get calls

### ISSUE THREAD

**Issue by thomasmmitchell** [cloudfoundry-community/go-cfclient#121]
Get(Org/Space/App/etc) gives an error if nothing was found with the expected input (name or GUID). There's not a good way (other than looking at the code and error string regex matching) to determine if the error was the result of an HTTP/TCP error or because nothing exists with the parameters the caller provided.

Usage of the library could be made more robust if we created public error types for these and returned the proper type of error depending on the cause of the problem.

**Comment by drnic** [comment]
Anyone have a preference for the style of error message? Any example golang projects that do this in a good way?

**Comment by thomasmmitchell** [comment]
Closed by #150
