### ISSUE TITLE
No app/service usage event helpers

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry-community/go-cfclient#132]
We want to start polling app and service usage events and was hoping to use this library, but it does not cover those endpoints. Is there any intention to add these in future?

http://apidocs.cloudfoundry.org/latest-release/app_usage_events/list_all_app_usage_events.html

**Comment by lnguyen** [comment]
Not currently, but feel free to make PR. It should be fairly simple, look at other endpoints as templates

**Comment by ckunst** [comment]
We just added support for App Usage Events in https://github.com/cloudfoundry-community/go-cfclient/pull/175

cc @jtuchscherer

**Comment by ckunst** [comment]
We just added also support for Service Usage events in https://github.com/cloudfoundry-community/go-cfclient/pull/176

cc @jtuchscherer
