### ISSUE TITLE
Support GA v3 APIs (organization of the overlapping struct names)

### ISSUE THREAD

**Issue by jcscottiii** [cloudfoundry-community/go-cfclient#151]
I have a use case that requires the current droplet information:
http://v3-apidocs.cloudfoundry.org/version/3.34.0/index.html#get-current-droplet
`GET /v3/apps/:guid/droplets/current`

As a result of the path, it would make sense to support the V3 App struct too but as we all know there's already a V2 App struct in this library.

And now that a bunch of the V3 APIs (not all) were marked GA in August, I'm wondering how we want to go about supporting the V3 APIs and objects in this library especially ones with overlapping struct names.

As a note: this library currently already has some v3 calls but none of them had pre-existing v2 equivalents.
https://github.com/cloudfoundry-community/go-cfclient/search?utf8=%E2%9C%93&q=v3&type=

A couple of ideas:
1. Break the package into two sub packages `v2` and `v3` like it does in the [java client](https://github.com/cloudfoundry/cf-java-client/tree/master/cloudfoundry-client/src/main/java/org/cloudfoundry/client).
  - Pros: it will make transitioning easier as more v3 apis go GA
  - Cons: huge refactor for people now
2. Prefix overlapping structs with `v3` (e.g. `V3App`)
  - Pros: not a huge refactor for library users
  - Cons: it feels way too dirty

I like the first one better but would love to know the thoughts of others / what would get accepted.

cc: @thomasmmitchell @lnguyen

**Comment by lnguyen** [comment]
I would prefer option one, we can always cut a v2 release and freeze it for existing people.

**Comment by thomasmmitchell** [comment]
The main problem with splitting the packages is going to be that, with most of the functions being members of the Client, we'd run into issues where we can't define more Client methods outside of the package in which client is defined (thanks, Go). We'd have to consider a call signature in which the client is taken as an argument, maybe?

**Comment by thePanz** [comment]
Another issue I am just facing: Errors objects from APIv2 and APIv3 are not compatible anymore:

V3 defines (http://v3-apidocs.cloudfoundry.org/version/3.41.0/index.html#errors)
```
{
  "errors": [
    {
      "code": 10008,
      "title": "CF-UnprocessableEntity",
      "detail": "something went wrong"
    }
  ]
}
```
While the client is currently unmarshalling errors as:
```
type CloudFoundryError struct {
	Code        int    `json:"code"`
	ErrorCode   string `json:"error_code"`
	Description string `json:"description"`
}
```

**Comment by mweibel** [comment]
FYI I started working on that.

> The main problem with splitting the packages is going to be that, with most of the functions being members of the Client, we'd run into issues where we can't define more Client methods outside of the package in which client is defined (thanks, Go). We'd have to consider a call signature in which the client is taken as an argument, maybe?

@thomasmmitchell could you explain your desired API a bit?

I thought of having two completely separate Clients, one for v2 and one for v3. This would allow us to have separate error handling and document in a clean way which APIs are available for which version. 

For users of the library, this most likely would mean maintaining two API clients at the same time, possibly also handling refreshing tokens etc. separately. Maybe this could be solved in another way? e.g. when instantiating a v3 client, a v2 client gets auto-instantiated as well? Then e.g. when new tokens are being fetched, those get assigned to the v2 client too. 

For the library it means we might have some code duplication but most likely on an acceptable level.

**Comment by XuejiaoZhang** [comment]
It would be really great to have V3 API Support. We have an application in Golang which calls API to get metadata of applications quite frequently. 
One option to improve performance for us is to use V3 API instead of V2.  But as we are using this go-cfclient library in our application, it's hard for us to switch API from V2 to V3. 

Here is a simple comparison between V2 and V3:
`# APIv2, 100 items per page
$ time cf-curl.sh -n /v2/apps?results-per-page=100 > /dev/null
real    1m12.812s
user    0m9.276s
sys     0m0.764s
# APIv3, 100 items per page
$ time cf-curl.sh -n /v3/apps?per_page=100 > /dev/null
real    0m30.478s
user    0m8.696s
sys     0m0.716s
# APIv3, 1000 items per page
$ time cf-curl.sh -n /v3/apps?per_page=1000 > /dev/null
real    0m15.402s
user    0m4.700s
sys     0m0.344s`
See more about the tool [cf-curl.sh](https://github.com/rakutentech/cf-tools/blob/master/cf-curl.sh) used above.

I would be very happy to know if you have any updates on this.

**Comment by gberche-orange** [comment]
Would the go-cfclient contributors be interested in joining forced with the CF CLI team working on the V3 api migration ? See related suggestion to CLI team at https://github.com/cloudfoundry/cli/issues/1481

**Comment by sneal** [comment]
Based on the current state of the code it looks like this decision has already been made to go with option 2, e.g. `Prefix overlapping structs with v3 (e.g. V3App)`
