### ISSUE TITLE
Consider removing `vendor` directory

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry-community/go-cfclient#152]
It's my understanding that including a `vendor` directory in a library (as opposed to a binary) is generally bad practice, at least according to [this 2016 tip](https://peter.bourgon.org/go-best-practices-2016/#top-tip-13).

I've encountered a similar issue today, where I'm trying to write code like this:

```golang
import (
	"github.com/cloudfoundry-community/go-cfclient"
	"golang.org/x/oauth2"
)

...

		cfclient.NewClient(&cfclient.Config{
			ApiAddress:  api,
			TokenSource: oauth2.StaticTokenSource(&oauth2.Token{AccessToken: at}),
		})
```

gives unhelpful errors like:

```
cannot use "golang.org/x/oauth2".StaticTokenSource(&"golang.org/x/oauth2".Token literal) (type "golang.org/x/oauth2".TokenSource) as type "github.com/cloudfoundry-community/go-cfclient/vendor/golang.org/x/oauth2".TokenSource in field value:
        "golang.org/x/oauth2".TokenSource does not implement "github.com/cloudfoundry-community/go-cfclient/vendor/golang.org/x/oauth2".TokenSource (wrong type for Token method)
                have Token() (*"golang.org/x/oauth2".Token, error)
                want Token() (*"github.com/cloudfoundry-community/go-cfclient/vendor/golang.org/x/oauth2".Token, error)
```

I can workaround by simply deleting the `vendor` dir from the `cf-client` library.

**Comment by aeijdenberg** [comment]
@jonathaningram - would be interested in your opinion re best practices for vendoring in Go libraries...

**Comment by jonathaningram** [comment]
@aeijdenberg my usual preference was that it should not be committed. I'm not sure how various "old" dependency tools like govendor work though. E.g. they may rely on it being committed.

Having said that, I think this ticket could go hand-in-hand with upgrading to `dep` and after a quick search, it looks like the choice is up to you: https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory

But, per https://github.com/golang/dep/issues/208, the dep lock file should be committed.
