### ISSUE TITLE
Bad credentials when using ClientID and ClientSecret

### ISSUE THREAD

**Issue by vChrisR** [cloudfoundry-community/go-cfclient#162]
When I use ClientID and ClientSecret to authenticate against CF i get this error {"error":"unauthorized","error_description":"Bad credentials"}

This actually worked fine when I was using an older version of the golang.org/x/oauth2 package (commit: ad516a2) but when I updated to commit 876b1c6 it stopped working.

Here is the code I used to test:

```
func main() {
	c := &cfclient.Config{
		ApiAddress:   "https://api.<redacted>",
		ClientID:     "<redacted>",
		ClientSecret: "<redacted>",
	}
	client, _ := cfclient.NewClient(c)
	svs, err := client.ListServices()
	if err != nil {
		fmt.Println(err)
	}
	for _, sv := range svs {
		fmt.Println(sv.Label)
	}
}
```
And here is the stdout:
```
go run main.go
Error requesting services: Get https://api.cf-prod.intranet.rws.nl/v2/services?: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"unauthorized","error_description":"Bad credentials"}
```

Again: this worked when golang/x/oauth2 package was at commit ad516a2

**Comment by vChrisR** [comment]
I actually found the commit that broke it in ouath2 lib: 13449ad91cb26cb47661c1b080790392170385fd
https://github.com/golang/oauth2/commit/13449ad91cb26cb47661c1b080790392170385fd

They added url.QueryEscape() to the ClientID and ClientSecret. So this break logging in with a secret containing special characters somehow. Which means UAA does not adhere strictly to the oauth spec.

**Comment by lancefrench** [comment]
Seems like uaa was modified to support the oauth spec in https://github.com/cloudfoundry/uaa/commit/6e938eb8f654a50bb57f7aca9cc9ab535631686d 

We could probably go back to a newer version of the library to fix issues with special characters in downstream consumers of this library.  E.g. https://github.com/bosh-prometheus/cf_exporter/issues/50

Please, let me know if you'd accept a pull request on this or want me to run down some user-space testing to validate.

**Comment by jghiloni** [comment]
We will totally take a PR
