### ISSUE TITLE
App: docker_credentials_json was renamed to docker_credentials

### ISSUE THREAD

**Issue by joefitzgerald** [cloudfoundry-community/go-cfclient#186]
In CC API [v260](https://apidocs.cloudfoundry.org/260/apps/list_all_apps.html), [`docker_credentials_json`](https://apidocs.cloudfoundry.org/259/apps/list_all_apps.html) was renamed to `docker_credentials`. This means that any use of `DockerCredentials` from the `App` struct is invalid for versions >= `2.82.0` of the CCAPI.

**Comment by sneal** [comment]
Since v260 has been around for years and `docker_credentials_json` was listed as experimental in v259 I'm inclined to make a breaking change and just rename it `docker_credentials` in this library.

**Comment by jghiloni** [comment]
Fixed in ed51ca3
