### ISSUE TITLE
V3 errors are different than V2 errors

### ISSUE THREAD

**Issue by kitemongerer** [cloudfoundry-community/go-cfclient#203]
The tasks code uses v3 endpoints but handles the errors returned as if they were v2 errors. Since the error responses are different between v2 and v3 (as shown below) this doesn't unmarshal into the `CloudFoundryError` object in errors.go. This makes handling certain errors (like app not found) impossible using the tasks helpers.

```
cf curl /v2/apps/sdaglk
{
   "description": "The app could not be found: sdaglk",
   "error_code": "CF-AppNotFound",
   "code": 100004
}
```

```
cf curl /v3/apps/sdaglk
{
   "errors": [
      {
         "detail": "App not found",
         "title": "CF-ResourceNotFound",
         "code": 10010
      }
   ]
}
```

**Comment by thePanz** [comment]
Duplicated of: #151

**Comment by thePanz** [comment]
@kitemongerer it is true that the `v3/tasks` API endpoint has been implemented, but the error handling is done with the V2 structure (https://github.com/cloudfoundry-community/go-cfclient/issues/151#issuecomment-376497215)

.. and that's quite a big issue IMHO

**Comment by thePanz** [comment]
@kitemongerer Have a look at the PR #216 , it implements a first handling of the two models of Errors for V2 and V3

**Comment by kitemongerer** [comment]
Looks great thanks!
