### ISSUE TITLE
Space.OrgData field isn't populated by GetSpaceByGuid

### ISSUE THREAD

**Issue by andrewgilbert12** [cloudfoundry-community/go-cfclient#205]
We assumed that the [OrgData field](https://github.com/cloudfoundry-community/go-cfclient/blob/49319a4a0c6f8b3f09af84053d0200cbf8523c17/spaces.go#L93) should be populated as the app.SpaceData.Entity.OrgData line is in [GetAppByGuid](
https://github.com/cloudfoundry-community/go-cfclient/blob/a0a191bdc19a7a7189c050444aeaf20d2a125875/apps.go#L249). Seems like unintuitive behavior that could be fixed by using inline-depth-relations=2, although this seems to be inefficient per https://github.com/cloudfoundry-community/go-cfclient/issues/31

**Comment by sneal** [comment]
I'm inclined to avoid using `inline-depth-relations=2` for performance reasons. Perhaps the v3 API offers better performance while simultaneously avoiding the unintuitive usage?

**Comment by sneal** [comment]
`GetAppByGuid` uses `inline-depth-relations=2` and returns the org data (https://github.com/cloudfoundry-community/go-cfclient/blob/a0a191bdc19a7a7189c050444aeaf20d2a125875/apps.go#L387).

There's a newer function to get this data without using `inline-depth-relations=2` https://github.com/cloudfoundry-community/go-cfclient/blob/f5b839ab27bd95208287bcdfb4a1f9ddbf5b76cd/apps.go#L280
