### ISSUE TITLE
Check for mocks being called

### ISSUE THREAD

**Issue by elgohr** [cloudfoundry-community/go-cfclient#219]
I introduced a check for seeing whether mocks are really called (see https://github.com/elgohr/go-cfclient/tree/mockCalled).
I needed this for TDD. Otherwise no implementation (simply return nil) would be a valid and the most easy implementation to fit the tests.
Nevertheless there are some tests failing after this.

I'm not sure if it would be a good idea to create a pull request for this, as Github mixes this with the other functionallity I requested for pull, which shouldn't be that controversial to discuss. In this way I would like to discuss this first.

**Comment by sneal** [comment]
It looks like the StartApp and StopApp functions which brought this up have since been added. I'll keep the wasCalled idea in mind if the need comes up.
