### ISSUE TITLE
Login broke after '--origin uaa' introduced in CF

### ISSUE THREAD

**Issue by akskap** [cloudfoundry-community/go-cfclient#224]
Hi,

Recently started noticing login issues with the library after auth mechanisms were modified in our CF deployment to use OIDC

Previously, the following code snippet used to work fine:

```
	CFConfig = &cfclient.Config{
		ApiAddress:        os.Getenv(constants.ENV_CF_API_URL),
		Username:          os.Getenv(constants.ENV_CF_USERNAME),
		Password:          os.Getenv(constants.ENV_CF_PASSWORD),
		SkipSslValidation: true,
	}
```
which has now started failing with the below error:

```
Error getting token: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"unauthorized","error_description":"Bad credentials"}
```

After OIDC was introduced, our CF CLI auth had to be appended by `--origin uaa` to function correctly.

Is there an equivalent feature in library as well ?

Thanks.

**Comment by jayam18** [comment]
@akskap I am running into the same problem you mentioned above. Did you get to solve it?

**Comment by sundarvc** [comment]
Same here getting this error when only logging in to a particular subdomain in CF. Other subdomains work.

**Comment by sneal** [comment]
Try adding origin in the config
```
CFConfig = &cfclient.Config{
  ApiAddress: os.Getenv(constants.ENV_CF_API_URL),
  Username:   os.Getenv(constants.ENV_CF_USERNAME),
  Password:    os.Getenv(constants.ENV_CF_PASSWORD),
  Origin:          "uaa",
  SkipSslValidation: true,
}
```

Origin is a new config option.
