### ISSUE TITLE
UpdateDetails look different to API definition

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/go-cfclient#230]
I was about to use the new https://github.com/cloudfoundry-community/go-cfclient/pull/218 and initially noticed a) the method `UpdateServiceInstance` does not consume the `UpdateDetails` struct, rather an unstructured `Reader`; b) the `UpdateDetails` struct does not look to match the API definition.

I might try to come back and investigate if `UpdateDetails` needs to be changed (b), and if `UpdateServiceInstance` can be upgraded to consume it rather than `Reader` (a); but will create this issue in the meantime in case I'm missing something.

API definition - https://apidocs.cloudfoundry.org/7.9.0/service_instances/update_a_service_instance.html

<img width="1172" alt="Screen Shot 2019-03-31 at 8 10 59 am" src="https://user-images.githubusercontent.com/108/55288893-8c8ba680-538c-11e9-9701-ef13b84d0ccf.png">

`UpdateDetails` struct has some different fields:

![image](https://user-images.githubusercontent.com/108/55288898-9b725900-538c-11e9-9ec4-7ed4a220a307.png)

**Comment by sneal** [comment]
#222 seems related
