### ISSUE TITLE
xsuaa broker launch via go-cfclient

### ISSUE THREAD

**Issue by linuxbsdfreak** [cloudfoundry-community/go-cfclient#231]
Hi,

I want to launch a xsuaa broker via the go-cfclient. What calls do i need to launch via the goclient? I am newbie to the cloudfoundry world. Could you point me to some sample code which i can refer ?

Regards,
Kevin

**Comment by sneal** [comment]
I'm not familiar with the xsuaa broker. If you're trying to push a broker app instance you're better off using the CF CLI at this point.
