### ISSUE TITLE
Does this library have the same function as 'cf ssh-code' ?

### ISSUE THREAD

**Issue by wangzeping722** [cloudfoundry-community/go-cfclient#246]
I want to implement such a function to access our container through webconsole. But I didn't find the same function as '**cf ssh-code**' in this library. Did I miss it?
[ssh-code Cloud Foundry CLI Reference Guide](http://cli.cloudfoundry.org/en-US/cf/ssh-code.html)

**Comment by sneal** [comment]
It does now thanks to you.
