### ISSUE TITLE
ListApps() method is redirecting the http post 

### ISSUE THREAD

**Issue by sudheerjunk** [cloudfoundry-community/go-cfclient#249]
I have created a Slackbot Application in GO and Deployed in CloudFoundry. It was working until i started using this ListApps() method from go-cfclient. Whenever I call this method, its looping for 10 times and calling the main post method and the whole application is looping for 10 times because of the usual redirect policy  to stop after 10 redirects.

c := &cfclient.Config{
		ApiAddress: apiURL,
		Username:   uname,
		Password:   upwd,
	}
	client, _ := cfclient.NewClient(c)

	apps, _ := client.ListApps()

Can someone help me resolve this issue

**Comment by sneal** [comment]
This doesn't sound like an issue with ListApps() or this library specifically.
