### ISSUE TITLE
Versioning could be implemented if breaking change is acceptable.

### ISSUE THREAD

**Issue by srbry** [cloudfoundry-community/go-cfclient#25]
A recent commit: https://github.com/cloudfoundry-community/go-cfclient/commit/0cdaf49f29f48a005592f43e3431d6f9475c30ed implemented a breaking change by changing the number of expected return arguments. Versioning the client via Tags and using http://labix.org/gopkg.in would allow changes like this to be made and only impact users that wish to get the new updates.

If versioning is not going to be implemented then improving the README to recommend using Godeps would be a good compromise.

**Comment by drnic** [comment]
@srbry good idea to add a notice about the lack of versions; I've put one in the readme. Perhaps future maintainers of this repo will start to version it somehow.
