### ISSUE TITLE
Login with sso or origin

### ISSUE THREAD

**Issue by astefanova** [cloudfoundry-community/go-cfclient#276]
Hi,

Is it possible to use the go-cfclient to login with `--sso` or `--origin`?

Kind regards,
Adriana

**Comment by jghiloni** [comment]
Not right now, but that's something I could investigate.

**Comment by sneal** [comment]
Origin support was added by #243. I'm not sure how prompting for a one-time passcode would work here. If there's a specific use case that origin doesn't cover feel free to open a new issue.
