### ISSUE TITLE
Rolling restart

### ISSUE THREAD

**Issue by hebelal** [cloudfoundry-community/go-cfclient#293]
Hi,

I just stumbled across the feature of cloud foundry to perform a [rolling restart](https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html#:~:text=guarantee%20zero%20downtime.-,Restart%20an%20App,-To%20restart%20your).
Is there a way to execute this command with this lib?

Best regards,
Alex

**Comment by sneal** [comment]
It looks like at a minimum the v3 deployment resource needs to be added to support this.

**Comment by d047491** [comment]
Hi,
You could manually implement something, that acts similar:
```	
instances, err := Cf.GetAppInstances(app.Guid)
for index := range instances {
	err = Cf.KillAppInstance(app.Guid, index)
	err = waitAllInstancesUp()
}
```
