### ISSUE TITLE
Restart App Instance

### ISSUE THREAD

**Issue by hebelal** [cloudfoundry-community/go-cfclient#294]
Hi,

Is it possible to restart only a single app instance, like with [restart-app-instance](https://cli.cloudfoundry.org/en-US/v6/restart-app-instance.html).

Best regards,
Alex

**Comment by sneal** [comment]
Not currently, but this could be added to v3apps.go with a PR if you're so inclined.

The CF CLI calls `DELETE` on [/v3/apps/:guid/processes/:type/instances/:index](https://v3-apidocs.cloudfoundry.org/version/3.111.0/index.html#terminate-a-process-instance) and lets the health management spin up a new instance.

**Comment by sneal** [comment]
Added to the v3 branch
