### ISSUE TITLE
IsXError is not aware of stdlib's errors.As

### ISSUE THREAD

**Issue by efd6** [cloudfoundry-community/go-cfclient#296]
Currently error type checks depend on the `github.com/pkg/errors.Cause` func, but the standard library makes available a similar functionality via `errors.As` which it not used by go-cfclient, though this dependency on pkg/errors is not documented.

I'm happy to send a PR adding support for stdlib error wrapping if this is acceptable.

**Comment by sneal** [comment]
PR? Yes please! I always thought it was a little odd we were using that 3rd party lib just for that one call.
