### ISSUE TITLE
Inline relations depth

### ISSUE THREAD

**Issue by joshq00** [cloudfoundry-community/go-cfclient#31]
Query parameter is deprecated and we've noticed it causes significant CPU load on cloud controller. Using the GraphQL model, I've noticed better efficiency with calling the specific URLs individually and aggregating the results. This also puts less load on each CC instance by avoiding unnecessary fetches

**Comment by drnic** [comment]
Sounds like a good plan to move away from using `inline-relations-depth=2` (currently in use by `apps.go` and `secgroups.go`). Whoever implements this will want to consider an appropriate parallelism method to make the depth calls to find child objects. Or, we make a breaking change and only return depth=1?

**Comment by tcdowney** [comment]
@drnic 

The `inline-relations-depth=2` on apps can also cause significant memory usage if the apps belong to spaces that have a large number of relationships themselves.

How bad would a breaking change here actually be given that the project isn't versioned and the README mentions this?

> NOTE: Currently this project is not versioning its releases and so breaking changes might be introduced. Whilst hopefully notifications of breaking changes are made via commit messages, ideally your project will use a local vendoring system to lock in a version of go-cfclient that is known to work for you. This will allow you to control the timing and maintenance of upgrades to newer versions of this library.

If I were a consumer I'd be a bit surprised that calling `ListApps` pulls so much data personally.

**Comment by sneal** [comment]
`inline-relations-depth` is deprecated in v2 but generally still works. Generally we should be moving towards v3 endpoints and leave v2 behavior as-is to avoid breaking consumers.
