### ISSUE TITLE
Support CF v3 API

### ISSUE THREAD

**Issue by EpsilonTal** [cloudfoundry-community/go-cfclient#312]
Hello,

I am using the `go-cfclient` and my platform is deprecating the `v2` cloud foundry API.
I wonder if you have plans or alternatives so I can integrate cloud foundry with the `v3` APIs.

For example, 
`github.com/cloudfoundry-community/go-cfclient/service_instances.go`
`GetServiceInstanceByGuid` is using the `v2` API: `c.NewRequest("GET", "/v2/service_instances/"+guid)`.
While I would like it to use the `v3` API.

Thanks.

**Comment by sneal** [comment]
There are no specific plans to fully implement the v3 API, however we encourage users to submit PRs that add the v3 API calls they need.

In the specific scenario you mentioned there is already some support for [getting service instance via the v3 API](https://github.com/cloudfoundry-community/go-cfclient/blob/34d8f2860a2049c1d6880face45c33b950de37a0/v3service_instances.go#L28) but no specific get by ID function yet.
