### ISSUE TITLE
There is no possibility to get credentials object from binding

### ISSUE THREAD

**Issue by uriyger** [cloudfoundry-community/go-cfclient#322]
Can't make such request via v3
https://api.example.org/v3/service_credential_bindings/dde5ad2a-d8f4-44dc-a56f-0452d744f1c3/details

**Comment by sneal** [comment]
I also added an [example](https://github.com/cloudfoundry-community/go-cfclient/blob/77cdcef10e385c8717ef0393d9cb2fb2ebfe26f5/examples/svc_creds/main.go)

**Comment by uriyger** [comment]
Wow that was fast. Thanks !
