### ISSUE TITLE
client supportability with Java application

### ISSUE THREAD

**Issue by Suyash08Oct** [cloudfoundry-community/go-cfclient#329]
I have few questions w.r.t client:
 1. As mentioned in the README.md, the v3.0.0-alpha.x release can have some breaking changes with respect to v3 implementation of cloud foundry. Is the client has all the specific necessary functions needed to interact the [Cloud Foundry](http://cloudfoundry.org/) Cloud Controller [v3 API](https://v3-apidocs.cloudfoundry.org/).
 2. Can this client be easily integrated with Java Spring Boot Based Applications.
 3. If Yes, Do we have any specific documentation to follow on the same.

**Comment by sneal** [comment]
1. This is a full v3 implementation.
2. Not really. You would need something that can call golang code from Java or convert Go code into Java code. There also might be a way to generate an OpenAPI spec from this client that would allow for the generation of a Java client. This client is fairly uniform.

**Comment by jghiloni** [comment]
@Suyash08Oct check out https://github.com/cloudfoundry/cf-java-client for the official CF java client, that works with spring boot

**Comment by sneal** [comment]
Thanks @jghiloni! I wrongly assumed the Java client didn't support v3 because of the Q.

**Comment by jghiloni** [comment]
Tbh I missed the v3 part but checked and it has support 😬
