### ISSUE TITLE
Add option for making API requests through CLI

### ISSUE THREAD

**Issue by afeld** [cloudfoundry-community/go-cfclient#33]
Hello! I'm interested in using this package as part of a Cloud Foundry CLI plugin, where it's preferable to make requests through `cf curl`, rather than passing credentials explicitly. Thoughts about exposing that as an option?

**Comment by allomov** [comment]
I am sure you can use [cf cli project](https://github.com/cloudfoundry/cli/blob/master/cf/api/curl.go) to run this command.

I am planning to use `code.cloudfoundry.org/cli/cf/api` package by myself right now. Do you see any concerns not to do it?

**Comment by data-henrik** [comment]
@afeld I have modified this go-cfclient to work within a cli plugin. I am obtaining the token from the cli environment to initialize the client credentials. I need to clean-up the code and would initialize a pull request plus upload my project to GH.
