### ISSUE TITLE
cfclient error (CF-InvalidAuthToken|1000): Invalid Auth Token

### ISSUE THREAD

**Issue by jameshochadel** [cloudfoundry-community/go-cfclient#349]
I can make API calls with the client when I've recently run a command with the cf CLI, because the CLI has used the refresh token to get a new access token. However, if I let the access token expire, I get the error in the title. 

Versions:

* CLI version: `cf version 8.2.0+fd8fbca64.2022-02-09`
* go-cfclient version: https://github.com/cloudfoundry-community/go-cfclient/releases/tag/v3.0.0-alpha.5
* cf API version: 3.147.0

**Comment by jameshochadel** [comment]
I looked at the open issues and noticed https://github.com/cloudfoundry-community/go-cfclient/issues/345, but I don't think the issue is the same. The refresh token works as expected with the cf CLI, so I don't think it's invalid or expiring.

**Comment by sneal** [comment]
I checked the CloudController and it returns a 401 status code with this error. I wonder if something is catching the http status before the executor gets it and tries to reauth.

**Comment by sneal** [comment]
Are you using `config.NewFromCFHomeDir()`? That doesn't read the refresh token, only the access token.

**Comment by sneal** [comment]
Fixed in 33e600b38b804df6fb04ac482851834f2bff074a

**Comment by jameshochadel** [comment]
Awesome — thank you @sneal, and sorry I didn't get back to you. I appreciate you following up on it.
