### ISSUE TITLE
Support other deployment strategies for CF Push

### ISSUE THREAD

**Issue by Gourab1998** [cloudfoundry-community/go-cfclient#377]
It would be great to have deployment strategies like blue-green and rolling in CF push to avoid interruption

**Comment by sneal** [comment]
That would be a nice addition. I personally don't have a reason to implement this yet, but perhaps you would want to take a stab at a PR?

**Comment by Gourab1998** [comment]
What are your thoughts about making all the optional fields in [manifest.go](https://github.com/cloudfoundry-community/go-cfclient/blob/main/operation/manifest.go) pointers instead of concrete types?
True, every field would then need a separate setter or pointer assignment, let me know your thoughts on this.
