### ISSUE TITLE
Create role via username and origin

### ISSUE THREAD

**Issue by Dray56** [cloudfoundry-community/go-cfclient#396]
**Problem**
For assigning a role to username, right now the go client only supports via user guid. For that we need to fetch the user details via possible filtered ListAll of users provided we have username. However suppose an org manager tries to fetch the guid of a user, that will only be possible if the user already is present in the org else the user will not appear in the ListAll results

**Solution**
To assign role via username and origin too as mentioned in cf [docs](https://v3-apidocs.cloudfoundry.org/version/3.154.0/index.html#create-a-role)

**Comment by sneal** [comment]
Thanks for the explanation
