### ISSUE TITLE
Allow setting a specific Useragent

### ISSUE THREAD

**Issue by janaurka** [cloudfoundry-community/go-cfclient#40]
Hey

This is a `feature request`.

I have opened a [feature request](https://github.com/cloudfoundry-community/cf_exporter/issues/2#issuecomment-268993721) at the [cf_exporter](https://github.com/cloudfoundry-community/cf_exporter) project to set a specific `useragent` value that the calls on the receiving end can be identified as `cf_exporter`. @frodenas mentioned, that `cf_exporter` uses this `client` to make the calls and that `go-cfclient` atm does not support setting a custom `useragent`.

Therefore: Can you please add the feature to set a custom `useragent`?

cheers

**Comment by shinji62** [comment]
I am working on a PR for that please wait a little bit.

Thanks

**Comment by shinji62** [comment]
Added here https://github.com/cloudfoundry-community/go-cfclient/pull/41

**Comment by frodenas** [comment]
Thanks @shinji62!
