### ISSUE TITLE
Take SkipSslValidation into account when getting token with oauth2

### ISSUE THREAD

**Issue by simonjohansson** [cloudfoundry-community/go-cfclient#8]
```
2015/05/08 14:28:57 Error getting token Post https://uaa.10.244.0.34.xip.io/oauth/token: x509: certificate signed by unknown authority
```

**Comment by simonjohansson** [comment]
I have sent a PR to oauth2 project to enable this functionality.

https://go-review.googlesource.com/#/c/9907/

**Comment by shinji62** [comment]
You can use your own ``` httpClient ``` I will try to check this today.

**Comment by simonjohansson** [comment]
@shinji62 
Oh crap, did not see this until I sent https://github.com/cloudfoundry-community/go-cfclient/pull/9
I hope I did not step on your toes.

**Comment by shinji62** [comment]
I rewrited  a little bit the goclient will PR tomorrow...

**Comment by shinji62** [comment]
close for now ? will reopen if my PR is not ok tomorow

**Comment by simonjohansson** [comment]
@shinji62 do you mean the issue or the other PR? :)

**Comment by shinji62** [comment]
No this issue ;)

Envoyé de mon iPhone

**Comment by simonjohansson** [comment]
@shinji62 ah, ok.

Is it not better though to let the issue be open until the issue is resolved?

**Comment by shinji62** [comment]
Ok let it open ;)

Envoyé de mon iPhone

**Comment by shinji62** [comment]
https://github.com/cloudfoundry-community/go-cfclient/pull/10

**Comment by simonjohansson** [comment]
Great, thanks!
